language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t aqrulesms/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true aqrulesms/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-react"
    env: "Dockerreact-env"
    bucket_name: "elasticbeanstalk-us-east-2-168116352293"
    bucket_path: "docker-react"
    on:
        branch: main
    access_key_id: "$AWS_ACCESS_KEY"
    secret_access_key:
        secure: "$AWS_SECRET_KEY"
